### ISSUE TITLE
General question..

### ISSUE THREAD

**Issue by EnZon3** [hackclub/replit-lifeboat#9]
Hey y'all, don't know where else to ask this.. but how long does it usually take to export?

Cheers

**Comment by NeonGamerBot-QK** [comment]
im currently in the middle of an export. its going OK so far.
> ![image](https://github.com/user-attachments/assets/c6fe08f4-c799-4d8c-a088-463578dc30f2)
cant do much about the errors theres no timed out requests at least.

**Comment by malted** [comment]
Hey! Each repl takes quite a while (on the order of minutes) because we have to connect to each file individually to get the history, so it really depends on how many repls you have!

It would be a good idea to add some duration metrics - I'll add it to my list of things to do.

**Comment by EnZon3** [comment]
> Hey! Each repl takes quite a while (on the order of minutes) because we have to connect to each file individually to get the history, so it really depends on how many repls you have!
> 
> It would be a good idea to add some duration metrics - I'll add it to my list of things to do.

why can't you just use Replit's official download link?

**Comment by malted** [comment]
It doesn't give you any history and fails to download big repls

**Comment by PotentialStyx** [comment]
> cant do much about the errors theres no timed out requests at least.

Failed repl downloads will soon be retried using the builtin repl download url (#11). Though this won't apply to accounts that have already run through the program, feel free to resubmit your account once that PR is merged and deployed

**Comment by NeonGamerBot-QK** [comment]
> im currently in the middle of an export. its going OK so far.
> 
> > ![image](https://private-user-images.githubusercontent.com/58448036/363798514-c6fe08f4-c799-4d8c-a088-463578dc30f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzMzQwMzksIm5iZiI6MTcyNTMzMzczOSwicGF0aCI6Ii81ODQ0ODAzNi8zNjM3OTg1MTQtYzZmZTA4ZjQtYzc5OS00ZDhjLWEwODgtNDYzNTc4ZGMzMGYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDAzMjIxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmYWU3YzdjZTE1ZDQ0YTQ3ZTA3NDhmOGVkYjc5NTNjNDNiMjcyODQ4MThjZGZkODI4MjVmMGFkZWYyYzFmN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mnxK_IUacwZ0g_EOt6cstVB1zPO7H8kjgefXpUWEXqk)
> > cant do much about the errors theres no timed out requests at least.

![image](https://github.com/user-attachments/assets/d37d5a35-ab3c-4a02-8405-1987fd6f045f)
4h later.. 
ive been doing it for around 8h i think

**Comment by PotentialStyx** [comment]
> 4h later.. ive been doing it for around 8h i think

BTW we are spinning up multiple instances so up to like 8 accounts should download at the same time, but yes download times are kinda slow rn

**Comment by NeonGamerBot-QK** [comment]
> > 4h later.. ive been doing it for around 8h i think
> 
> BTW we are spinning up multiple instances so up to like 8 accounts should download at the same time, but yes download times are kinda slow rn

It’s all good I got like a lot of repls anyways I think around a couple gigs

**Comment by NeonGamerBot-QK** [comment]
> > 4h later.. ive been doing it for around 8h i think
> 
> BTW we are spinning up multiple instances so up to like 8 accounts should download at the same time, but yes download times are kinda slow rn

nvm, i forgot to check my email and i found out it finished a couple hours back. 
it also gives you a list to the failed installs which is very nice!

**Comment by malted** [comment]
Adding an ETA indicator on the website which should alleviate this!
